/*
 * generated by Xtext
 */
package org.neclipse.xtext.entitydsl.ui.contentassist

import org.neclipse.xtext.entitydsl.ui.contentassist.AbstractEntityDslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class EntityDslProposalProvider extends AbstractEntityDslProposalProvider {
}
