/*
* generated by Xtext
*/
package org.neclipse.xtext.training.smallfunc.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.neclipse.xtext.training.smallfunc.services.SmallFuncDslGrammarAccess;

public class SmallFuncDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private SmallFuncDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.neclipse.xtext.training.smallfunc.parser.antlr.internal.InternalSmallFuncDslParser createParser(XtextTokenStream stream) {
		return new org.neclipse.xtext.training.smallfunc.parser.antlr.internal.InternalSmallFuncDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Namespace";
	}
	
	public SmallFuncDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SmallFuncDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
