/*
 * generated by Xtext
 */
package org.neclipse.xtext.functiondsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractFunctionDslValidator extends org.neclipse.xtext.parentdsl.validation.ParentDslValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(org.neclipse.xtext.functiondsl.functionDsl.FunctionDslPackage.eINSTANCE);
		return result;
	}
}
