/*
* generated by Xtext
*/
package org.neclipse.xtext.parentdsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ParentDslStandaloneSetup extends ParentDslStandaloneSetupGenerated{

	public static void doSetup() {
		new ParentDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

