/*
 * generated by Xtext
 */
package org.neclipse.xtext.parentdsl;

import org.neclipse.xtext.parentdsl.scoping.ParentImportedNamespaceAwareLocalScopeProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ParentDslRuntimeModule extends org.neclipse.xtext.parentdsl.AbstractParentDslRuntimeModule {

	@Override
    public final void configureIScopeProviderDelegate(final com.google.inject.Binder binder) {
        binder.bind(org.eclipse.xtext.scoping.IScopeProvider.class)
              .annotatedWith(com.google.inject.name.Names.named(org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider.NAMED_DELEGATE))
              .to(ParentImportedNamespaceAwareLocalScopeProvider.class);
    }
	
}
