/*
 * generated by Xtext
 */
package org.neclipse.xtext.functiondsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class FunctionDslUiModule extends org.neclipse.xtext.functiondsl.ui.AbstractFunctionDslUiModule {
	public FunctionDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
