/*
* generated by Xtext
*/
package org.neclipse.xtext.entitydsl.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.neclipse.xtext.entitydsl.services.EntityDslGrammarAccess;

public class EntityDslParser extends AbstractContentAssistParser {
	
	@Inject
	private EntityDslGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.neclipse.xtext.entitydsl.ui.contentassist.antlr.internal.InternalEntityDslParser createParser() {
		org.neclipse.xtext.entitydsl.ui.contentassist.antlr.internal.InternalEntityDslParser result = new org.neclipse.xtext.entitydsl.ui.contentassist.antlr.internal.InternalEntityDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getDataTypeAccess().getAlternatives(), "rule__DataType__Alternatives");
					put(grammarAccess.getNamespaceDefinitionAccess().getGroup(), "rule__NamespaceDefinition__Group__0");
					put(grammarAccess.getEntityAccess().getGroup(), "rule__Entity__Group__0");
					put(grammarAccess.getAttributeAccess().getGroup(), "rule__Attribute__Group__0");
					put(grammarAccess.getEntityReferenceAccess().getGroup(), "rule__EntityReference__Group__0");
					put(grammarAccess.getStringTypeAccess().getGroup(), "rule__StringType__Group__0");
					put(grammarAccess.getStringTypeAccess().getGroup_2(), "rule__StringType__Group_2__0");
					put(grammarAccess.getStringTypeAccess().getGroup_2_4(), "rule__StringType__Group_2_4__0");
					put(grammarAccess.getNamespaceDeclarationAccess().getGroup(), "rule__NamespaceDeclaration__Group__0");
					put(grammarAccess.getImportDeclarationAccess().getGroup(), "rule__ImportDeclaration__Group__0");
					put(grammarAccess.getImportAccess().getGroup(), "rule__Import__Group__0");
					put(grammarAccess.getQualifedNameAccess().getGroup(), "rule__QualifedName__Group__0");
					put(grammarAccess.getQualifedNameAccess().getGroup_1(), "rule__QualifedName__Group_1__0");
					put(grammarAccess.getQualifedNameWithWildcardAccess().getGroup(), "rule__QualifedNameWithWildcard__Group__0");
					put(grammarAccess.getNamespaceDefinitionAccess().getNamespaceDeclarationAssignment_0(), "rule__NamespaceDefinition__NamespaceDeclarationAssignment_0");
					put(grammarAccess.getNamespaceDefinitionAccess().getImportDeclarationAssignment_1(), "rule__NamespaceDefinition__ImportDeclarationAssignment_1");
					put(grammarAccess.getNamespaceDefinitionAccess().getArtifactAssignment_2(), "rule__NamespaceDefinition__ArtifactAssignment_2");
					put(grammarAccess.getEntityAccess().getNameAssignment_2(), "rule__Entity__NameAssignment_2");
					put(grammarAccess.getEntityAccess().getAttributesAssignment_4(), "rule__Entity__AttributesAssignment_4");
					put(grammarAccess.getAttributeAccess().getNameAssignment_0(), "rule__Attribute__NameAssignment_0");
					put(grammarAccess.getAttributeAccess().getTypeAssignment_2(), "rule__Attribute__TypeAssignment_2");
					put(grammarAccess.getEntityReferenceAccess().getEntityAssignment_1(), "rule__EntityReference__EntityAssignment_1");
					put(grammarAccess.getStringTypeAccess().getNameAssignment_1(), "rule__StringType__NameAssignment_1");
					put(grammarAccess.getStringTypeAccess().getLengthAssignment_2_3(), "rule__StringType__LengthAssignment_2_3");
					put(grammarAccess.getStringTypeAccess().getDefaultValueAssignment_2_4_3(), "rule__StringType__DefaultValueAssignment_2_4_3");
					put(grammarAccess.getNamespaceDeclarationAccess().getNameAssignment_1(), "rule__NamespaceDeclaration__NameAssignment_1");
					put(grammarAccess.getImportDeclarationAccess().getImportsAssignment_1(), "rule__ImportDeclaration__ImportsAssignment_1");
					put(grammarAccess.getImportAccess().getImportedNamespaceAssignment_1(), "rule__Import__ImportedNamespaceAssignment_1");
					put(grammarAccess.getArtifactAccess().getNameAssignment(), "rule__Artifact__NameAssignment");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.neclipse.xtext.entitydsl.ui.contentassist.antlr.internal.InternalEntityDslParser typedParser = (org.neclipse.xtext.entitydsl.ui.contentassist.antlr.internal.InternalEntityDslParser) parser;
			typedParser.entryRuleNamespaceDefinition();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public EntityDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(EntityDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
