/*
* generated by Xtext
*/
package org.neclipse.xtext.parentdsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class ParentDslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.neclipse.xtext.parentdsl.ui.internal.ParentDslActivator.getInstance().getInjector("org.neclipse.xtext.parentdsl.ParentDsl");
	}
	
}
