/*
 * generated by Xtext
 */
package org.neclipse.xtext.training.smallJava;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SmallJavaDslRuntimeModule extends org.neclipse.xtext.training.smallJava.AbstractSmallJavaDslRuntimeModule {

}
