/*
 * generated by Xtext
 */
package org.neclipse.xtext.entitydsl.scoping;

/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation.html#scoping
 * on how and when to use it 
 *
 */
public class EntityDslScopeProvider extends org.neclipse.xtext.parentdsl.scoping.ParentDslScopeProvider {

}
