/*
 * generated by Xtext
 */
package org.neclipse.xtext.functiondsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.neclipse.xtext.functiondsl.ui.internal.FunctionDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class FunctionDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FunctionDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return FunctionDslActivator.getInstance().getInjector(FunctionDslActivator.ORG_NECLIPSE_XTEXT_FUNCTIONDSL_FUNCTIONDSL);
	}
	
}
