/*
 * generated by Xtext
 */
package org.neclipse.xtend.training.smallJava.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SmallJavaDslUiModule extends org.neclipse.xtend.training.smallJava.ui.AbstractSmallJavaDslUiModule {
	public SmallJavaDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
