/*
 * generated by Xtext
 */
package org.neclipse.xtext.training.smallfunc.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.neclipse.xtext.training.smallfunc.ui.internal.SmallFuncDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SmallFuncDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SmallFuncDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SmallFuncDslActivator.getInstance().getInjector(SmallFuncDslActivator.ORG_NECLIPSE_XTEXT_TRAINING_SMALLFUNC_SMALLFUNCDSL);
	}
	
}
