/*
 * generated by Xtext
 */
package org.neclipse.xtext.training.smallfunc.ui.contentassist

import org.neclipse.xtext.training.smallfunc.ui.contentassist.AbstractSmallFuncDslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class SmallFuncDslProposalProvider extends AbstractSmallFuncDslProposalProvider {
}
