/*
* generated by Xtext
*/
package org.neclipse.xtext.training.smallJava;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class SmallJavaDslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.neclipse.xtext.training.smallJava.ui.internal.SmallJavaDslActivator.getInstance().getInjector("org.neclipse.xtext.training.smallJava.SmallJavaDsl");
	}
	
}
