/*
* generated by Xtext
*/
package org.neclipse.xtext.entitydsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class EntityDslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.neclipse.xtext.entitydsl.ui.internal.EntityDslActivator.getInstance().getInjector("org.neclipse.xtext.entitydsl.EntityDsl");
	}
	
}
