/*
* generated by Xtext
*/
package org.neclipse.xtext.entitydsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class EntityDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/neclipse/xtext/entitydsl/parser/antlr/internal/InternalEntityDsl.tokens");
	}
}
