/*
* generated by Xtext
*/
package org.neclipse.xtext.functiondsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class FunctionDslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.neclipse.xtext.functiondsl.ui.internal.FunctionDslActivator.getInstance().getInjector("org.neclipse.xtext.functiondsl.FunctionDsl");
	}
	
}
