/*
 * generated by Xtext
 */
package org.neclipse.xtext.entitydsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class EntityDslRuntimeModule extends org.neclipse.xtext.entitydsl.AbstractEntityDslRuntimeModule {

}
