/*
* generated by Xtext
*/
package org.neclipse.xtext.training.smallfunc;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class SmallFuncDslStandaloneSetup extends SmallFuncDslStandaloneSetupGenerated{

	public static void doSetup() {
		new SmallFuncDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

