/*
 * generated by Xtext
 */
package org.neclipse.xtext.training.smallfunc;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SmallFuncDslRuntimeModule extends org.neclipse.xtext.training.smallfunc.AbstractSmallFuncDslRuntimeModule {

}
