/*
 * generated by Xtext
 */
package org.neclipse.xtext.training.smallfunc.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SmallFuncDslUiModule extends org.neclipse.xtext.training.smallfunc.ui.AbstractSmallFuncDslUiModule {
	public SmallFuncDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
