/*
* generated by Xtext
*/
package org.neclipse.xtext.functiondsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class FunctionDslStandaloneSetup extends FunctionDslStandaloneSetupGenerated{

	public static void doSetup() {
		new FunctionDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

