/*
 * generated by Xtext
 */
package org.neclipse.xtext.parentdsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ParentDslUiModule extends org.neclipse.xtext.parentdsl.ui.AbstractParentDslUiModule {
	public ParentDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
