/*
* generated by Xtext
*/
package org.neclipse.xtext.training.smallfunc;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class SmallFuncDslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.neclipse.xtext.training.smallfunc.ui.internal.SmallFuncDslActivator.getInstance().getInjector("org.neclipse.xtext.training.smallfunc.SmallFuncDsl");
	}
	
}
