/*
 * generated by Xtext
 */
package org.neclipse.xtext.functiondsl.ui.contentassist

import org.neclipse.xtext.functiondsl.ui.contentassist.AbstractFunctionDslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class FunctionDslProposalProvider extends AbstractFunctionDslProposalProvider {
}
