/*
* generated by Xtext
*/
package org.neclipse.xtext.functiondsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class FunctionDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/neclipse/xtext/functiondsl/parser/antlr/internal/InternalFunctionDsl.tokens");
	}
}
