/*
 * generated by Xtext
 */
package org.neclipse.xtext.entitydsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractEntityDslValidator extends org.neclipse.xtext.parentdsl.validation.ParentDslValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(org.neclipse.xtext.entitydsl.entityDsl.EntityDslPackage.eINSTANCE);
		return result;
	}
}
