/*
* generated by Xtext
*/
package org.neclipse.xtext.parentdsl.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.neclipse.xtext.parentdsl.services.ParentDslGrammarAccess;

public class ParentDslParser extends AbstractContentAssistParser {
	
	@Inject
	private ParentDslGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.neclipse.xtext.parentdsl.ui.contentassist.antlr.internal.InternalParentDslParser createParser() {
		org.neclipse.xtext.parentdsl.ui.contentassist.antlr.internal.InternalParentDslParser result = new org.neclipse.xtext.parentdsl.ui.contentassist.antlr.internal.InternalParentDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getNamespaceDefinitionAccess().getGroup(), "rule__NamespaceDefinition__Group__0");
					put(grammarAccess.getNamespaceDeclarationAccess().getGroup(), "rule__NamespaceDeclaration__Group__0");
					put(grammarAccess.getImportDeclarationAccess().getGroup(), "rule__ImportDeclaration__Group__0");
					put(grammarAccess.getImportAccess().getGroup(), "rule__Import__Group__0");
					put(grammarAccess.getQualifedNameAccess().getGroup(), "rule__QualifedName__Group__0");
					put(grammarAccess.getQualifedNameAccess().getGroup_1(), "rule__QualifedName__Group_1__0");
					put(grammarAccess.getQualifedNameWithWildcardAccess().getGroup(), "rule__QualifedNameWithWildcard__Group__0");
					put(grammarAccess.getNamespaceDefinitionAccess().getNamespaceDeclarationAssignment_0(), "rule__NamespaceDefinition__NamespaceDeclarationAssignment_0");
					put(grammarAccess.getNamespaceDefinitionAccess().getImportDeclarationAssignment_1(), "rule__NamespaceDefinition__ImportDeclarationAssignment_1");
					put(grammarAccess.getNamespaceDefinitionAccess().getArtifactAssignment_2(), "rule__NamespaceDefinition__ArtifactAssignment_2");
					put(grammarAccess.getNamespaceDeclarationAccess().getNameAssignment_1(), "rule__NamespaceDeclaration__NameAssignment_1");
					put(grammarAccess.getImportDeclarationAccess().getImportsAssignment_1(), "rule__ImportDeclaration__ImportsAssignment_1");
					put(grammarAccess.getImportAccess().getImportedNamespaceAssignment_1(), "rule__Import__ImportedNamespaceAssignment_1");
					put(grammarAccess.getArtifactAccess().getNameAssignment(), "rule__Artifact__NameAssignment");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.neclipse.xtext.parentdsl.ui.contentassist.antlr.internal.InternalParentDslParser typedParser = (org.neclipse.xtext.parentdsl.ui.contentassist.antlr.internal.InternalParentDslParser) parser;
			typedParser.entryRuleNamespaceDefinition();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public ParentDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ParentDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
