/*
 * generated by Xtext
 */
package org.neclipse.xtext.parentdsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.neclipse.xtext.parentdsl.ui.internal.ParentDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ParentDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ParentDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ParentDslActivator.getInstance().getInjector(ParentDslActivator.ORG_NECLIPSE_XTEXT_PARENTDSL_PARENTDSL);
	}
	
}
