/*
 * generated by Xtext
 */
package org.neclipse.xtext.parentdsl.ui.contentassist

import org.neclipse.xtext.parentdsl.ui.contentassist.AbstractParentDslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class ParentDslProposalProvider extends AbstractParentDslProposalProvider {
}
