/*
 * generated by Xtext
 */
package org.neclipse.xtext.training.smallJava.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.ComposedChecks;

@ComposedChecks(validators= {org.eclipse.xtext.validation.NamesAreUniqueValidator.class})
public class AbstractSmallJavaDslValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(org.neclipse.xtext.training.smallJava.smallJavaDsl.SmallJavaDslPackage.eINSTANCE);
		return result;
	}
}
