/*
 * generated by Xtext
 */
package org.neclipse.xtext.parentdsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractParentDslValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(org.neclipse.xtext.parentdsl.parentDsl.ParentDslPackage.eINSTANCE);
		return result;
	}
}
